on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Lint GitHub Actions
        uses: super-linter/super-linter@v7.4.0
        env:
          FILTER_REGEX_INCLUDE: .*github/workflows/.*
      - run: git diff --exit-code
      - name: Lint Code Base
        uses: super-linter/super-linter@v7.4.0
      - run: git diff --exit-code
        if: ${{ github.event_name != 'pull_request' }}
      - run: git config --global user.email ${{ github.actor }}@users.noreply.github.com
      - run: git config --global user.name ${{ github.actor }}
      - run: git checkout "$GITHUB_HEAD_REF"
        if: ${{ github.event_name == 'pull_request' }}
      - run: git branch --set-upstream-to=origin/"$GITHUB_HEAD_REF"
        if: ${{ github.event_name == 'pull_request' }}
      - run: git add --update
      - run: >
          git commit -m "chore(super-linter): close and reopen PR now"
        continue-on-error: true
      - run: git pull --rebase
      - run: git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FILTER_REGEX_EXCLUDE: CHANGELOG.md
      VALIDATE_PYTHON_PYINK: false
      FIX_ANSIBLE: true
      FIX_CLANG_FORMAT: true
      FIX_CSHARP: true
      FIX_CSS_PRETTIER: true
      FIX_CSS: true
      FIX_DOTNET_SLN_FORMAT_ANALYZERS: true
      FIX_DOTNET_SLN_FORMAT_STYLE: true
      FIX_DOTNET_SLN_FORMAT_WHITESPACE: true
      FIX_ENV: true
      FIX_GO_MODULES: true
      FIX_GO: true
      FIX_GOOGLE_JAVA_FORMAT: true
      FIX_GRAPHQL_PRETTIER: true
      FIX_GROOVY: true
      FIX_HTML_PRETTIER: true
      FIX_JAVASCRIPT_ES: true
      FIX_JAVASCRIPT_PRETTIER: true
      FIX_JAVASCRIPT_STANDARD: true
      FIX_JSON_PRETTIER: true
      FIX_JSON: true
      FIX_JSONC: true
      FIX_JSONC_PRETTIER: true
      FIX_JSX_PRETTIER: true
      FIX_JSX: true
      FIX_MARKDOWN_PRETTIER: true
      FIX_MARKDOWN: true
      FIX_POWERSHELL: true
      FIX_PROTOBUF: true
      FIX_PYTHON_BLACK: true
      FIX_PYTHON_ISORT: true
      FIX_PYTHON_RUFF: true
      FIX_RUBY: true
      FIX_RUST_2015: true
      FIX_RUST_2018: true
      FIX_RUST_2021: true
      FIX_RUST_CLIPPY: true
      FIX_SCALAFMT: true
      FIX_SHELL_SHFMT: true
      FIX_SNAKEMAKE_SNAKEFMT: true
      FIX_SQLFLUFF: true
      FIX_TERRAFORM_FMT: true
      FIX_TSX: true
      FIX_TYPESCRIPT_ES: true
      FIX_TYPESCRIPT_PRETTIER: true
      FIX_TYPESCRIPT_STANDARD: true
      FIX_VUE_PRETTIER: true
      FIX_YAML_PRETTIER: true
